### ISSUE TITLE
Backend having trouble with poetry install

### ISSUE THREAD

**Issue by JocelynYH** [bgreenawald/madgab-online#32]
Even when wiping the virtual env and reinstalling from fresh, scipy and pandas aren't installing.  Hence, the backend can't run. 

The error logs are too long, but here are some highlights:
Pandas not installing:
```
          raise Exception(
      Exception: Cython-generated file 'pandas/_libs/algos.c' not found.
                      Cython is required to compile pandas from a development branch.
                      Please install Cython or download a release package of pandas.

      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-req-build-059he0zf/setup.py'"'"'; __file__='"'"'/private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-req-build-059he0zf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-record-ig02v_e_/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/include/site/python3.9/pandas Check the logs for full command output.


  at /usr/local/Cellar/poetry/1.1.3/libexec/lib/python3.9/site-packages/poetry/utils/env.py:948 in _run
       944│                 output = subprocess.check_output(
       945│                     cmd, stderr=subprocess.STDOUT, **kwargs
       946│                 )
       947│         except CalledProcessError as e:
    →  948│             raise EnvCommandError(e, input=input_)
       949│
       950│         return decode(output)
       951│
       952│     def execute(self, bin, *args, **kwargs):
```
Scipy not installing:
```
    customize UnixCCompiler using build_clib
    building 'mach' library
    error: library mach has Fortran sources but no Fortran compiler found
    ----------------------------------------
    ERROR: Failed building wheel for scipy
  Failed to build scipy
  ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly


  at /usr/local/Cellar/poetry/1.1.3/libexec/lib/python3.9/site-packages/poetry/utils/env.py:948 in _run
       944│                 output = subprocess.check_output(
       945│                     cmd, stderr=subprocess.STDOUT, **kwargs
       946│                 )
       947│         except CalledProcessError as e:
    →  948│             raise EnvCommandError(e, input=input_)
       949│
       950│         return decode(output)
       951│
       952│     def execute(self, bin, *args, **kwargs):

```
Cython (recommended from pandas install failure logs) not installing:
```

  • Installing cython (0.29.21)
  • Installing pandas (0.25.3): Failed

  EnvCommandError

  Command ['/Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/bin/pip', 'install', '--no-deps', 'file:///Users/jocelyn/Library/Caches/pypoetry/artifacts/62/89/4c/d4382189ac9884b84a417972f36996807a6535a25ee8102ba0d3dfc32b/pandas-0.25.3.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/jocelyn/Library/Caches/pypoetry/artifacts/62/89/4c/d4382189ac9884b84a417972f36996807a6535a25ee8102ba0d3dfc32b/pandas-0.25.3.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-req-build-jrq5ivjo/setup.py'"'"'; __file__='"'"'/private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-req-build-jrq5ivjo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-pip-egg-info-7jacejx_
           cwd: /private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-req-build-jrq5ivjo/
      Complete output (23 lines):
      init_dgelsd failed init
      Traceback (most recent call last):
        File "/Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 343, in get_provider
          module = sys.modules[moduleOrReq]
      KeyError: 'numpy'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-req-build-jrq5ivjo/setup.py", line 815, in <module>
          ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
        File "/private/var/folders/fz/0qzlx9xd14qc5k8s0z7dvbmc0000gn/T/pip-req-build-jrq5ivjo/setup.py", line 537, in maybe_cythonize
          numpy_incl = pkg_resources.resource_filename("numpy", "core/include")
        File "/Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1128, in resource_filename
          return get_provider(package_or_requirement).get_resource_filename(
        File "/Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 345, in get_provider
          __import__(moduleOrReq)
        File "/Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
          raise RuntimeError(msg)
      RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
      RankWarning: Polyfit may be poorly conditioned

      ----------------------------------------
  WARNING: Discarding file:///Users/jocelyn/Library/Caches/pypoetry/artifacts/62/89/4c/d4382189ac9884b84a417972f36996807a6535a25ee8102ba0d3dfc32b/pandas-0.25.3.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


  at /usr/local/Cellar/poetry/1.1.3/libexec/lib/python3.9/site-packages/poetry/utils/env.py:948 in _run
       944│                 output = subprocess.check_output(
       945│                     cmd, stderr=subprocess.STDOUT, **kwargs
       946│                 )
       947│         except CalledProcessError as e:
    →  948│             raise EnvCommandError(e, input=input_)
       949│
       950│         return decode(output)
       951│
       952│     def execute(self, bin, *args, **kwargs):

  • Installing scipy (1.5.3): Installing...
```

Solutions already tried:
wiping and reinstalling virtualenv.
installing Cython (failed)
upgrading pip
blindly googling errors and trying random solutions

**Comment by bgreenawald** [comment]
Hmm, I'm unable to replicate locally, either with Windows or Ubuntu.

@JocelynYH What version of Mac OS are you running?

Further, what happens when you try:
1. Installing via _pip_ ```pip install -r requirements.txt```
2. Attempting to install _scipy_ on its own?

I know _scipy_ can be a pain to install on some systems, but isolating this to a _scipy_ vs a _poetry_ issue would be helpful.

**Comment by JocelynYH** [comment]
2. Didn't work - for both pandas and scipy.  The env says it's already installed
```
The following packages are already present in the pyproject.toml and will be skipped:

  • scipy

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.
```

```
The following packages are already present in the pyproject.toml and will be skipped:

  • pandas

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.
```

**Comment by JocelynYH** [comment]
MacOS is 10.15.6

**Comment by JocelynYH** [comment]
Hmm, getting a similar error with pip.  Would make sense, because is poetry using pip under the hood? 
``` customize UnixCCompiler
  #### ['clang', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-fno-common', '-dynamic', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-isysroot', '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk', '-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include', '-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers'] #######
  customize UnixCCompiler using build_clib
  building 'mach' library
  error: library mach has Fortran sources but no Fortran compiler found
  ----------------------------------------
  ERROR: Failed building wheel for scipy
Failed to build pandas scipy
ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
```

**Comment by JocelynYH** [comment]
Additionally, this is the error I get when I run `python app.py` in the shell.  Figured it's due to poetry install/pip install not working properly - because maybe it's not.
```
Python(96114,0x10e6c7dc0) malloc: can't allocate region
:*** mach_vm_map(size=18446744072489172992, flags: 100) failed (error code=3)
Python(96114,0x10e6c7dc0) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "/Users/jocelyn/Github/madgab-online/backend/app.py", line 16, in <module>
    from game import Game, InvalidState
  File "/Users/jocelyn/Github/madgab-online/backend/game.py", line 8, in <module>
    from madgab.madgab import mad_gabify
  File "/Users/jocelyn/Github/madgab-online/backend/madgab/madgab.py", line 5, in <module>
    import numpy as np
  File "/Users/jocelyn/Library/Caches/pypoetry/virtualenvs/madgab-online-OIuOxmt5-py3.9/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

**Comment by JocelynYH** [comment]
I did make sure to install numpy

**Comment by JocelynYH** [comment]
Hmm, okay interesting - both the chalkful and madgab backends work with my desktop (macOS 10.13.4 and python version 3.7.7)

**Comment by bgreenawald** [comment]
That is so strange... The only insights I could find were from Google (which it sounds like you already did). Other than making sure _pip_ is upgraded and the Fortran compiler is correctly installed, I'm not coming up with much.

Has it _ever_ worked on your laptop? It could be that I updated the packages and the newer version somehow isn't compatible with newer Mac OS'

**Comment by bgreenawald** [comment]
![Screenshot_20210130-185308](https://user-images.githubusercontent.com/8428972/106370878-735b3480-632c-11eb-80b2-eab322765105.jpg)

Pretty much all I got.

**Comment by JocelynYH** [comment]
LOL thanks for the comic.  I have a suspicision: My laptop (broken) is using python 3.9 while creating new poetry envs.  Do you know how I can tell poetry to use 3.7?  The pyproject.toml should take care of that right?

**Comment by bgreenawald** [comment]
That is a very strong theory. It looks like the _pyproject.toml_ requires at least 3.7, but it should forbid more recent distributions of 3. You could try changing the line 
```bash
python = "^3.7"
```
to
```bash
python = "3.7"
```
before running the _poetry_ installation and see if that helps.

**Comment by JocelynYH** [comment]
just threw me another error: 
```
The currently activated Python version 3.9.1 is not supported by the project (3.7).
Trying to find and use a compatible version.

  NoCompatiblePythonVersionFound

  Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.

  at /usr/local/Cellar/poetry/1.1.4/libexec/lib/python3.9/site-packages/poetry/utils/env.py:735 in create_venv
       731│                     python_minor = ".".join(python_patch.split(".")[:2])
       732│                     break
       733│
       734│             if not executable:
    →  735│                 raise NoCompatiblePythonVersionFound(
       736│                     self._poetry.package.python_versions
       737│                 )
       738│
       739│         if root_venv:

```

Online suggestions say to use pyenv to change the version first then run the poetry install.  Is that... okay? Just seems weird to have a virtual environment for your virtual environment.

**Comment by JocelynYH** [comment]
That is what I've done at work though, but with pyenv then pipenv

**Comment by bgreenawald** [comment]
This is definitely an ok solution if it works!

**Comment by JocelynYH** [comment]
FINALLY got things working - for reference, I used this thread: https://github.com/python-poetry/poetry/issues/651

I ended up having to `brew uninstall poetry` and reinstall using the curl command on the official documentation's install instructions.  I also did end up spawning a pyenv shell, but with that alone, poetry still kept using 3.9.
